---
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1006
      - PGID=1002
      - TZ=Europe/Zurich
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /data/deluge/config:/config
      - /data/arr/data/torrents:/data/torrents
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    networks:
      - mediaservernet
    hostname: deluge
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1006
      - PGID=1002
      - TZ=Europe/Zurich
    volumes:
      - /data/radarr/config:/config
      - /data/arr/data:/data
      # using hardlink
      # - /path/to/movies:/movies #optional
      # - /path/to/download-client-downloads:/downloads #optional
    ports:
      - 7878:7878
    networks:
      - mediaservernet
    hostname: radarr
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1006
      - PGID=1002
      - TZ=Europe/Zurich
    volumes:
      - /data/sonarr/config:/config
      - /data/arr/data:/data
      # using hardlink
      # - /path/to/movies:/movies #optional
      # - /path/to/download-client-downloads:/downloads #optional
    ports:
      - 8989:8989
    networks:
      - mediaservernet
    hostname: sonarr
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1006
      - PGID=1002
      - TZ=Europe/Zurich
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /data/jackett/config:/config
      - /data/arr/data:/data
    ports:
      - 9117:9117
    networks:
      - mediaservernet
    hostname: jackett
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1006
      - PGID=1002
      - TZ=Europe/Zurich
      - DOCKER_MODS:linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /data/jellyfin/config:/config
      - /data/arr/data/media/tv:/data/tvshows
      - /data/arr/data/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - mediaservernet
    hostname: jellyfin
    restart: unless-stopped

networks:
  mediaservernet:
    driver: bridge
